spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/itellyou?useUnicode=true&useAffectedRows=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: wangji520
      initial-size: 10
      min-idle: 10
      max-active: 600
      max-wait: 30000
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
mybatis:
  type-aliases-package: com.itellyou.model
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:mapper/**/*Mapper.xml
  configuration:
    default-enum-type-handler: com.itellyou.dao.handler.EnumTypeHandler
    map-underscore-to-camel-case: true