INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_collab', 10016, 1589078645, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_comment_child_list', 10016, 1589078648, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_comment_root_list', 10016, 1589078652, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_detail', 10016, 1589078663, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_grab', 10016, 1592038041, 1754599596);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_group_list', 10016, 1596706073, 83994816);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_list', 10016, 1596715297, 83994816);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_version_compare', 10016, 1589078742, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_version_detail', 10016, 1589078744, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_version_list', 10016, 1589078746, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (1, 'api_software_view', 10016, 1589078748, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_comment_create', 10016, 1589077628, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_comment_delete', 10016, 1589077629, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_comment_oppose', 10016, 1589077643, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_comment_support', 10016, 1589077648, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_content', 10016, 1589077650, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_create', 10016, 1589077651, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_delete', 10016, 1589077655, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_draft', 10016, 1589077659, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_draft_delete', 10016, 1589077660, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_edit', 10016, 1589077663, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_file_recommend', 10016, 1597208906, 134326464);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_meta', 10016, 1589077664, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_oppose', 10016, 1589077666, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_publish', 10016, 1589077667, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_rollback', 10016, 1589077671, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (2, 'api_software_support', 10016, 1589077676, 16777343);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_collab', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_comment_child_list', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_comment_create', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_comment_delete', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_comment_oppose', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_comment_root_list', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_comment_support', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_content', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_create', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_delete', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_detail', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_draft', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_draft_delete', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_edit', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_file_recommend', 10016, 1597208936, 134326464);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_grab', 10016, 1597208937, 134326464);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_group_list', 10016, 1597208938, 134326464);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_list', 10016, 1597208939, 134326464);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_meta', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_oppose', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_publish', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_related', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_rollback', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_support', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_version_compare', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_version_detail', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_version_list', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_role_permission`(`role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) VALUES (3, 'api_software_view', 10016, 0, 0);
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_collab', 2, 1, 2, '/software/collab', '获取软件协作编辑数据');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_comment_child_list', 2, 1, 1, '/software/{softwareId:\\d+}/comment/child', '获取软件子评论列表');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_comment_create', 2, 1, 3, '/software/{softwareId:\\d+}/comment/create', '创建软件评论');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_comment_delete', 2, 1, 4, '/software/{softwareId:\\d+}/comment/{id:\\d+}', '删除软件评论');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_comment_oppose', 2, 1, 2, '/software/{softwareId:\\d+}/comment/{id:\\d+}/{type:oppose}', '反对软件评论');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_comment_root_list', 2, 1, 1, '/software/{softwareId:\\d+}/comment/root', '获取软件根评论列表');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_comment_support', 2, 1, 2, '/software/{softwareId:\\d+}/comment/{id:\\d+}/{type:support}', '点赞软件评论');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_content', 2, 1, 3, '/software/{id:\\d+}/content', '提交编辑内容到软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_create', 2, 1, 2, '/software/create', '新建软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_delete', 2, 1, 4, '/software/{id:\\d+}', '删除软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_detail', 2, 1, 1, '/software/{id:\\d+}', '获取软件详情');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_draft', 2, 1, 1, '/software/{id:\\d+}/user_draft', '获取当前用户软件草稿');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_draft_delete', 2, 1, 4, '/software/{id:\\d+}/user_draft', '删除当前用户软件草稿');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_edit', 2, 1, 1, '/software/{id:\\d+}/edit', '编辑软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_file_recommend', 2, 1, 2, '/software/{softwareId:\\d+}/file/{fileId:\\d+}/recommend', '设置软件文件是否为推荐');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_grab', 2, 1, 2, '/software/grab', '采集itellyou.cn软件后上传的api');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_group_list', 2, 1, 1, '/software/group/list', '下载软件分组列表');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_list', 2, 1, 1, '/software/list', '软件列表');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_meta', 2, 1, 3, '/software/{id:\\d+}/meta', '提交编辑属性到软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_oppose', 2, 1, 2, '/software/{id:\\d+}/{type:oppose}', '反对软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_publish', 2, 1, 3, '/software/{id:\\d+}/publish', '发布软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_rollback', 2, 1, 3, '/software/{id:\\d+}/rollback', '回滚软件版本');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_support', 2, 1, 2, '/software/{id:\\d+}/{type:support}', '点赞软件');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_version_compare', 2, 1, 1, '/software/{softwareId:\\d+}/version/{current:\\d+}...{target:\\d+}', '对比软件版本详情');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_version_detail', 2, 1, 1, '/software/{softwareId:\\d+}/version/{versionId:\\d+}', '获取软件版本详情');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_version_list', 2, 1, 1, '/software/{softwareId:\\d+}/version', '获取软件版本列表');
INSERT INTO `itellyou`.`sys_permission`(`name`, `platform`, `type`, `method`, `data`, `remark`) VALUES ('api_software_view', 2, 1, 1, '/software/{id:\\d+}/view', '记录浏览软件的数据');
