insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_tag_group_create', '3', '1', '3', '/tag/group', '创建标签分组');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_tag_group_edit', '3', '1', '2', '/tag/group', '编辑标签分组');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_tag_group_remove', '3', '1', '4', '/tag/group', '删除标签分组');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_tag_group_list', '3', '1', '1', '/tag/group', '获取标签列表');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_tag_edit', '3', '1', '2', '/tag/{id:\\d+}', '编辑标签基本信息');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_tag_group_create', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_tag_group_edit', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_tag_group_remove', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_tag_group_list', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_tag_edit', '10012', '0', '0');
insert into `itellyou`.`sys_setting` ( `key`, `name`, `logo`, `icp_text`, `copyright`, `company_name`, `user_agreement_link`, `footer_scripts`) values ( 'default', 'ITELLYOU', '', '蜀ICP备17019166号', 'Copyright © 2020', '四川西维尔科技有限公司', '', '');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'api_sys_setting', '1', '1', '1', '/system/setting', '获取系统设置');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'api_sys_link_list', '1', '1', '1', '/system/link', '获取友情链接列表');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_sys_setting_edit', '3', '1', '2', '/system/setting', '编辑系统设置');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_sys_link_create', '3', '1', '3', '/system/link', '新增友情链接');
insert into `itellyou`.`sys_permission` ( `name`, `platform`, `type`, `method`, `data`, `remark`) values ( 'admin_sys_link_remove', '3', '1', '4', '/system/link', '删除友情链接');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '1', 'api_sys_setting', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '1', 'api_sys_link_list', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'api_sys_link_list', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'api_sys_setting', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_sys_setting_edit', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_sys_link_create', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '3', 'admin_sys_link_remove', '10012', '0', '0');
insert into `itellyou`.`sys_role_permission` ( `role_id`, `permission_name`, `created_user_id`, `created_time`, `created_ip`) values ( '1', 'api_preview', '10012', '0', '0');
